gText_Birch_Welcome::
	.string "Hi! Look at my cool POKéMON!!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This little freak is called LOTAD”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I boosted the base stats of probably\n"
	.string "every single POKéMON, to even the field.\p"
	.string "I changed tons of their abilities\n"
	.string "and added new moves they can learn.\l"
	.string "Also all evolutions are now possible.\p"
	.string "It's worth noting that all 1025\n"
	.string "POKéMON now have an attacking stat!\p"
	.string "So you can use FORRETRESS or TOXAPEX\n"
	.string "and not make your experience miserable.\p"
	.string "I hope you can use your favorite.\n"
	.string "POKéMON without worry for power!\p"
	.string "There are Generations 1 through 9. and\n"
	.string "a ton of bonus little changes for you!\p"
	.string "I added a lot of hidden secrets, so I\n"
	.string "hope you'll enjoy exploring the region!\p"
	.string "There is something new in probably every\n"
	.string "single area, and entirely new locations!\p"
	.string "So whenever you reach a new place, have\n"
	.string "a look around for what I left for you!\l"
	.string "\l"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Do you wanna play as a BADDIE?\n"
	.string "Or are you a CLOWN?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What should we call you?$"

gText_Birch_SoItsPlayer::
	.string "So it's EUGENE?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're EUGENE who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
