PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "My kids been hanging out with one\n"
	.string "of our new GYM LEADERs.\p"
	.string "He won't shut up about some dog.\n"
	.string "We've never even had one.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I just lost my dog...\p"
	.string "And my brother told me how to chaaaase\p"
	.string "the bag.\p"
	.string "Get right in the field, I had to make\n"
	.string "a bag.\p"
	.string "The day he lost his soul,\n"
	.string "wish I could take it back...$"
