PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "VIGOROTH! VIG VIG!\p"
	.string "Boruto is the greatest show.\n"
	.string "VIGOROTH! VIG VIG!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sorry, he's kinda just the muscle.\p"
	.string "He just spews unintelligible nonsense.$"

