PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "VIGOROTH! VIG VIG!\p"
	.string "Boruto is the greatest show ever made!\p"
	.string "VIGOROTH! VIG VIG!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sorry, he's a bit of a 'diversity hire'.\p"
	.string "His mom begged me to hire him for the\n"
	.string "muscle since he can't do much else..$"

